# Gradle Properties
org.gradle.jvmargs = -Xmx1G
org.gradle.parallel = true

# Mod Properties
version = dev-1.4.9-light
maven_group = net.arjun
archives_base_name = pool

# Dependencies are managed at gradle/libs.versions.toml

#org.gradle.daemon=true
#org.gradle.caching=true
#org.gradle.configuration-cache=true
org.gradle.offline=true

